Try again to build other platforms.

diff --git a/.github/workflows/mac-build.yml b/.github/workflows/mac-build.yml
--- a/.github/workflows/mac-build.yml
+++ b/.github/workflows/mac-build.yml
@@ -4,6 +4,7 @@ on:
     branches:
     - "main"
     - "core-9-0-branch"
+    - "7f67bb4054d6d7d9-menu-recursive-chw"
     tags:
     - "core-**"
 permissions:
@@ -16,13 +17,18 @@ jobs:
     defaults:
       run:
         shell: bash
+        working-directory: tk/macosx
     steps:
-      - name: Checkout
+      - name: Checkout Tk
         uses: actions/checkout@v6
-      - name: Fetch Tcl
-        run: |
-          curl -L -O https://core.tcl-lang.org/tcl/tarball/main/tcl.tar.gz
-          tar xfz tcl.tar.gz
+        with:
+          path: tk
+      - name: Check out Tcl 9.1
+        uses: actions/checkout@v6
+        with:
+          repository: tcltk/tcl
+          ref: main
+          path: tcl
       - name: Prepare checked out repositories
         run: |
           touch tk/generic/tkStubInit.c
@@ -32,24 +38,135 @@ jobs:
         working-directory: .
       - name: Build Tcl
         run: |
-          make -C macosx
-        working-directory: tcl
-      - name: Build Tk
+          make all
+        working-directory: tcl/macosx
+      - name: Build
         run: |
-          make -C macosx || {
+          make all install || {
             echo "::error::Failure during Build"
             exit 1
           }
-        working-directory: tk
       - name: Run Tests
         run: |
-          make -C macosx TK_NO_STDERR=1 test | tee out.txt
+          make TK_NO_STDERR=1 test | tee out.txt
           nmatches=$( grep -c "Failed	0" out.txt )
           if [ $nmatches -lt 4 ]
           then
             echo "::error::Failure during Test"
             exit 1
           fi
-        working-directory: tk
         timeout-minutes: 30
-
+  prefix:
+    runs-on: macos-26
+    strategy:
+      matrix:
+        symbols:
+          - 'no'
+          - 'mem'
+        options:
+          - '--enable-aqua'
+          - '--disable-aqua'
+    defaults:
+      run:
+        shell: bash
+        working-directory: tk/unix
+    steps:
+      - name: Checkout Tk
+        uses: actions/checkout@v6
+        with:
+          path: tk
+      - name: Check out Tcl 9.1
+        uses: actions/checkout@v6
+        with:
+          repository: tcltk/tcl
+          ref: main
+          path: tcl
+      - name: Prepare checked out repositories
+        env:
+          SET_DISPLAY: ${{ contains(matrix.options, '--disable-aqua') }}
+        run: |
+          touch tkStubInit.c
+          mkdir "$HOME/install dir"
+          echo "USE_XVFB=$SET_DISPLAY" >> $GITHUB_ENV
+        working-directory: tk/generic
+      - name: Add X11 (if required)
+        if: ${{ env.USE_XVFB == 'true' }}
+        run: |
+          brew install --cask xquartz
+          sudo /opt/X11/libexec/privileged_startx || true
+        working-directory: .
+      - name: Build Tcl
+        run: |
+          ./configure $CFGOPT --disable-zipfs "--prefix=$HOME/install dir" || {
+            cat config.log
+            echo "::error::Failure during Tcl Configure"
+            exit 1
+          }
+          make all || {
+            echo "::error::Failure during Tcl Build"
+            exit 1
+          }
+          make install || {
+            echo "::error::Failure during Tcl Install"
+            exit 1
+          }
+        working-directory: tcl/unix
+        env:
+          CFGOPT: --enable-symbols=${{ matrix.symbols }}
+      - name: Configure (symbols=${{ matrix.symbols }} ${{matrix.options }})
+        run: |
+          ./configure $CFGOPT --disable-zipfs "--prefix=$HOME/install dir" --disable-xft || {
+            cat config.log
+            echo "::error::Failure during Configure"
+            exit 1
+          }
+        env:
+          CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{matrix.options }}
+      - name: Build
+        run: |
+          make all tktest || {
+            echo "::error::Failure during Build"
+            exit 1
+          }
+      - name: Run Tests
+        run: |
+          if [ $USE_XVFB == true ]; then
+            function runXvfb {
+              PATH=$PATH:/opt/X11/bin
+              Xvfb $1 &
+              XVFB_PID=$!
+              echo Launched Xvfb $1 as process $XVFB_PID >&2
+              trap "echo killing process $XVFB_PID... >&2; kill $XVFB_PID" 0
+              export DISPLAY=$1
+              sleep 2
+            }
+          else
+            function runXvfb {
+              echo Xvfb not used, this is a --enable-aqua build
+              export TK_NO_STDERR=1
+            }
+          fi
+          ( runXvfb :0; make test-classic; exit $? ) | tee out-classic.txt || {
+            echo "::error::Failure during Test (classic)"
+            exit 1
+          }
+          ( runXvfb :0; make test-ttk; exit $? ) | tee out-ttk.txt || {
+            echo "::error::Failure during Test (ttk)"
+            exit 1
+          }
+          cat out-classic.txt | grep -q "Failed	0" || {
+            echo "::error::Failure in classic test results"
+            exit 1
+          }
+          cat out-ttk.txt | grep -q "Failed	0" || {
+            echo "::error::Failure in ttk test results"
+            exit 1
+          }
+        timeout-minutes: 20
+      - name: Carry out trial installation
+        run: |
+          make install || {
+            cat config.log
+            echo "::error::Failure during Install"
+            exit 1
+          }
